### ISSUE TITLE
Getting non-iterator error for solr_itr, of variable type of SolrRequestIter

### ISSUE THREAD

**Issue by MichaelARoberts** [o19s/solr-to-es#17]
Python version 3.8.2

Here's my request: `solr-to-es http://localhost:18983/solr/furniture http://localhost:9200 products furniture`

And here's my tracestack:
```
Traceback (most recent call last):
  File "c:\users\michael\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\michael\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38-32\Scripts\solr-to-es.exe\__main__.py", line 7, in <module>
  File "c:\users\michael\appdata\local\programs\python\python38-32\lib\site-packages\solr_to_es\__main__.py", line 97, in main
    es_actions = SolrEsWrapperIter(solr_itr, args['elasticsearch_index'], args['doc_type'])
  File "c:\users\michael\appdata\local\programs\python\python38-32\lib\site-packages\solr_to_es\__main__.py", line 11, in __init__
    self.solr_itr = iter(solr_itr)
TypeError: iter() returned non-iterator of type 'SolrRequestIter'
```

**Comment by epugh** [comment]
Thanks @MichaelARoberts for submitting this issue.  This tool project gets only sporadic maintence, basically when someone needs it, so if you have a PR I'll be happy to test it and merge it.   

I wonder if it's not Python3 friendly?

Also, on a similar project, `solr_dump`, I moved to just using the Requests library, and you might be interested in just changing solr-to-es to the same pattern.  see https://github.com/o19s/solr_dump/pull/2 for inspiration.

**Comment by epugh** [comment]
Thanks to @cstech-carl-camilleri this issue is fixed!
